# fly.toml app configuration file generated for flappy-small-breeze-7809 on 2024-08-13T00:23:14+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'flappy-small-breeze-1337'
primary_region = 'syd'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
